### ISSUE TITLE
Repeater updates first and animates second

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/animator-css#48]
I'm following [this guide](http://blog.durandal.io/2015/07/17/animating-apps-with-aurelia-part-1/) and expected to see something like:

![expected behaviour](http://blog.durandal.io/content/images/2015/07/list-staggered-animate.gif)

Instead I got:

![actual behaviour](http://i.imgur.com/ZnoYGY0.gif)

Not sure what I'm doing wrong: my code is essentially the same as in the guide.

```html
<template class="au-stagger">
	<div repeat.for="item of feedbackService.items" class="au-animate feedback-item level-${item.level}">
		<a click.trigger="feedbackService.removeItem(item)" href="#" class="fa fa-times-circle"></a>
		<p>${item.message}</p>
	</div>
</template>
```

```ts
export class FeedbackService {

	private static REMOVE_DELAY_MS = 5000;

	public items: FeedbackItem[] = [];

	addItem(item: FeedbackItem) {
		this.items.push(item);
		if (item.autohide) {
			setTimeout(
				() => this.removeItem(item),
				FeedbackService.REMOVE_DELAY_MS * this.items.filter((item) => item.autohide).length
			);
		}
	}

	removeItem(item: FeedbackItem) {
		let index = this.items.indexOf(item);
		if (index > -1) {
			this.items.splice(index, 1);
		}
	}
}
```

```scss
.feedback-item {
	&.au-enter {
		max-height: 0;
	}
	&.au-enter-active {
		animation: feedbackUp 1s;
	}
	&.au-leave-active {
		animation: feedbackDown 1s;
	}
}

@keyframes feedbackUp {
    0%   { max-height: 0; }
    100% { max-height: 102px; }
}

@keyframes feedbackDown {
    0%   { max-height: 102px; }
    100% { max-height: 0; }
}
```
